AllCops:
  TargetRubyVersion: 2.4

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/GuardClause:
  MinBodyLength: 5

# Disable Metric checks for specs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Guardfile'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'
    - Gemfile

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false
